### ISSUE TITLE
Application broke with update to SageMath 7.2

### ISSUE THREAD

**Issue by Bomberus** [MathJunkie/MathJunkie_Laravel#32]
Cannot connect to external Calculation Engine because of JS Error.

**Comment by Bomberus** [comment]
Unfortunatly our application broke down because SageMath JS has incorperated RequireJS and it seems our script and theirs try to define the same modules and get in each others "way". Should be fixed with the newest branch. #31

**Comment by Bomberus** [comment]
Please test if the issue is resolved.
For productive Test: https://mathjunkie.bomberus.de

**Comment by SimonLangDev** [comment]
sage math is running now, but the header is missing

**Comment by Bomberus** [comment]
There was an mistake in the routes.php file. I updated the branch #31
